name: Tests

on:
  push:
    paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']
    branches:
    - 'master'
    - 'release/version*'
    - 'bugfix/actions'
  pull_request:
    paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']

jobs:
  # Build the code and run the unit/integration tests.
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-build-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-build-
          ${{ runner.os }}-maven-format-
          ${{ runner.os }}-maven-
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
    - name: Build and Run Unit Tests
      run: |
        RUN_TESTS="mvn -V -B -e -Pdev,examples,assemble -Ddist -T1C clean verify"
        $RUN_TESTS \
          || { echo "***** TESTS FAILED. Attempting retry."; $RUN_TESTS; } \
          || { echo "***** TESTS FAILED. Attempting final retry."; $RUN_TESTS; }
      env:
        MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Djava.awt.headless=true"
